### ISSUE TITLE
Outdated Chromium

### ISSUE THREAD

**Issue by spantaleev** [kool-dev/pdf#19]
This `Dockerfile` is based on `kooldev/puppeteer:latest` (published 2 years ago), which currently seems to contain Chromium `81.0.4044.113`, with the current version being `93.0.4577.82`.

There seems to be a `1.0`-tagged image of `kooldev/puppeteer`, which seems newer (published a month ago).

It'd be great if `kooldev/puppeteer:latest` got rebuilt/republished, or even better if `kool-dev/pdf` switched to using the `1.0` tag (or some other, newer, published tag) of `kooldev/puppeteer`.

**Comment by fabriciojs** [comment]
We have latest `1.2.0` version upgraded to Chromium 93.0.4577.82!
